### ISSUE TITLE
Add New Lockdown Post and Fix Previous Posts Formatting

### ISSUE THREAD

**Issue by UneatenStaple** [ragaeeb/das-js#436]
**To Do**
- [x] Fix formatting of most recent posts to include bold and underlining
- [x] Add new lockdown post regarding the updated stay at home order

**Comment by ragaeeb** [comment]
Branch [issue-436-Add_New_Lockdown_Post_and_Fix_Previous_Posts_Formatting](https://github.com/ragaeeb/das-js/tree/issue-436-Add_New_Lockdown_Post_and_Fix_Previous_Posts_Formatting) created!
