### ISSUE TITLE
Update Fajr, Dhuhr and 'Ishaa Iqama Times for February/March 2022

### ISSUE THREAD

**Issue by UneatenStaple** [ragaeeb/das-js#642]
Update Fajr Iqama time to 6:00 am for February 21-28. Update Fajr Iqama time to 6:30 am, Dhuhr Iqama time to 1:30 pm, 'Ishaa Iqama time to 8:45 pm, and Jumuah Iqama times to 1:00 pm and 1:45 pm starting March 13th. Update Fajr Iqama time to 6:10 am and 'Ishaa Iqama time to 9:00 pm starting March 21st.

**Comment by ragaeeb** [comment]
Branch [issue-642-Update_Fajr_Dhuhr_and_Ishaa_Iqama_Times_for_February/March_2022](https://github.com/ragaeeb/das-js/tree/issue-642-Update_Fajr_Dhuhr_and_Ishaa_Iqama_Times_for_February/March_2022) created!
