### ISSUE TITLE
Update Jumua Kutbah Time to Single Kutbah

### ISSUE THREAD

**Issue by UneatenStaple** [ragaeeb/das-js#653]
With recent ease of restrictions, there will be only 1 kutbah held at the musalla moving forward. Update Jumua kutbah adhan time to reflect this.

**Comment by ragaeeb** [comment]
Branch [issue-653-Update_Jumua_Kutbah_Time_to_Single_Kutbah](https://github.com/ragaeeb/das-js/tree/issue-653-Update_Jumua_Kutbah_Time_to_Single_Kutbah) created!
