### ISSUE TITLE
Create Post for Lifting of Capacity Restrictions

### ISSUE THREAD

**Issue by UneatenStaple** [ragaeeb/das-js#655]
With recent restriction changes in Ontario, the musalla is open at full capacity with no distancing restrictions. This should be posted on the website.

**Comment by ragaeeb** [comment]
Branch [issue-655-Create_Post_for_Lifting_of_Capacity_Restrictions](https://github.com/ragaeeb/das-js/tree/issue-655-Create_Post_for_Lifting_of_Capacity_Restrictions) created!
