### ISSUE TITLE
Remove Donation Section from Home Page

### ISSUE THREAD

**Issue by UneatenStaple** [ragaeeb/das-js#659]
Any method of donation presented on the website needs to be removed, which appears to only be the donation section on the home page. This will require slightly modifying the style for the about section so that the about and contact section are contiguous.

**Comment by ragaeeb** [comment]
Branch [issue-659-Remove_Donation_Section_from_Home_Page](https://github.com/ragaeeb/das-js/tree/issue-659-Remove_Donation_Section_from_Home_Page) created!
