### ISSUE TITLE
Remove Mixlr Link in Latest Pre-Ramadhan Class Post

### ISSUE THREAD

**Issue by UneatenStaple** [ragaeeb/das-js#666]
Remove Mixlr link from most recent post as it will not be broadcast.

**Comment by ragaeeb** [comment]
Branch [issue-666-Remove_Mixlr_Link_in_Latest_Pre-Ramadhan_Class_Post](https://github.com/ragaeeb/das-js/tree/issue-666-Remove_Mixlr_Link_in_Latest_Pre-Ramadhan_Class_Post) created!
